import { Resource, EmergencyRequest, Complaint, Volunteer, PlatformStats, NotificationItem, WeatherInfo } from '../types';

export const INITIAL_MOCK_RESOURCES: Resource[] = [
  {
    _id: 'res-1',
    name: 'City Care Multi-Specialty Hospital',
    category: 'Hospitals',
    description: '24/7 Tertiary care hospital with specialized ICU units, trauma care, and oxygen generation plant.',
    contact: {
      phone: '+91 98765 43210',
      email: 'emergency@citycare.org',
      website: 'https://citycarehospital.org',
    },
    address: {
      street: '45 Healthcare Boulevard, MG Road Area',
      city: 'Central City',
      state: 'State Central',
      pincode: '400001',
      fullAddress: '45 Healthcare Boulevard, MG Road Area, Central City - 400001',
    },
    location: {
      type: 'Point',
      coordinates: [72.8777, 19.0760], // Longitude, Latitude
    },
    availability: {
      beds: 42,
      icuBeds: 8,
      oxygenCylinders: 65,
      status: 'AVAILABLE',
      notes: 'Trauma ward open. Ventilators available in ICU-2.',
      lastUpdated: new Date(Date.now() - 15 * 60000).toISOString(),
    },
    operatingHours: '24/7 Open',
    verified: true,
    rating: 4.8,
    reviewsCount: 312,
    distanceKm: 1.8,
    status: 'ACTIVE',
    createdAt: new Date('2026-01-10').toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'res-2',
    name: 'Apex LifeCare Pharmacy',
    category: 'Pharmacies',
    description: '24-hour authentic medicine dispending center stocking essential critical care and emergency drugs.',
    contact: {
      phone: '+91 98765 12345',
      email: 'orders@apexlifecare.com',
    },
    address: {
      street: '12 Station Road, Opposite Metro Gate 3',
      city: 'Central City',
      state: 'State Central',
      pincode: '400002',
      fullAddress: '12 Station Road, Opposite Metro Gate 3, Central City - 400002',
    },
    location: {
      type: 'Point',
      coordinates: [72.8820, 19.0790],
    },
    availability: {
      status: 'AVAILABLE',
      notes: 'Full stock of viral antivirals, antibiotics, and pediatric drops.',
      lastUpdated: new Date(Date.now() - 40 * 60000).toISOString(),
    },
    operatingHours: '24/7 Open',
    verified: true,
    rating: 4.9,
    reviewsCount: 184,
    distanceKm: 2.3,
    status: 'ACTIVE',
    createdAt: new Date('2026-01-12').toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'res-3',
    name: 'Metropolitan Red Cross Blood Bank',
    category: 'Blood Banks',
    description: 'State-certified blood transfusion center providing tested whole blood, PRBC, and single donor platelets.',
    contact: {
      phone: '+91 98220 99887',
      email: 'donor@redcrossblood.org',
    },
    address: {
      street: '8 Red Cross Drive, Civil Lines',
      city: 'Central City',
      state: 'State Central',
      pincode: '400005',
      fullAddress: '8 Red Cross Drive, Civil Lines, Central City - 400005',
    },
    location: {
      type: 'Point',
      coordinates: [72.8650, 19.0680],
    },
    availability: {
      bloodGroupsAvailable: ['O+', 'A+', 'B+', 'O-', 'AB+'],
      status: 'AVAILABLE',
      notes: 'O- Negative emergency units reserved.',
      lastUpdated: new Date(Date.now() - 5 * 60000).toISOString(),
    },
    operatingHours: '8:00 AM - 10:00 PM (Emergency 24/7)',
    verified: true,
    rating: 4.7,
    reviewsCount: 95,
    distanceKm: 3.1,
    status: 'ACTIVE',
    createdAt: new Date('2026-01-15').toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'res-4',
    name: 'Sahya Community Relief Shelter & Food Kitchen',
    category: 'Food Support',
    description: 'Community-led warm meal distribution center and temporary overnight shelter with clean sanitation.',
    contact: {
      phone: '+91 91234 56789',
      email: 'relief@sahya.org',
    },
    address: {
      street: 'Community Hall, Sector 4, Greenfield',
      city: 'Central City',
      state: 'State Central',
      pincode: '400010',
      fullAddress: 'Community Hall, Sector 4, Greenfield, Central City - 400010',
    },
    location: {
      type: 'Point',
      coordinates: [72.8910, 19.0850],
    },
    availability: {
      foodPackets: 350,
      status: 'AVAILABLE',
      notes: 'Fresh hot meals served from 12 PM - 3 PM and 7 PM - 9:30 PM.',
      lastUpdated: new Date(Date.now() - 60 * 60000).toISOString(),
    },
    operatingHours: '7:00 AM - 10:00 PM',
    verified: true,
    rating: 4.9,
    reviewsCount: 220,
    distanceKm: 4.2,
    status: 'ACTIVE',
    createdAt: new Date('2026-02-01').toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'res-5',
    name: 'PureAir Emergency Medical Oxygen Hub',
    category: 'Oxygen',
    description: 'Medical oxygen refilling and cylinder home delivery center equipped with high-purity medical oxygen.',
    contact: {
      phone: '+91 98111 22334',
      email: 'help@pureairoxygen.in',
    },
    address: {
      street: 'Plot 78, Industrial Estate Phase II',
      city: 'Central City',
      state: 'State Central',
      pincode: '400015',
      fullAddress: 'Plot 78, Industrial Estate Phase II, Central City - 400015',
    },
    location: {
      type: 'Point',
      coordinates: [72.8600, 19.0920],
    },
    availability: {
      oxygenCylinders: 48,
      status: 'AVAILABLE',
      notes: 'B-type and D-type cylinders in stock. Oxygen concentrators available for rent.',
      lastUpdated: new Date(Date.now() - 10 * 60000).toISOString(),
    },
    operatingHours: '24/7 Open',
    verified: true,
    rating: 4.6,
    reviewsCount: 140,
    distanceKm: 3.8,
    status: 'ACTIVE',
    createdAt: new Date('2026-01-20').toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'res-6',
    name: 'RapidRescue ALS Ambulance Fleet',
    category: 'Ambulances',
    description: 'Advanced Life Support (ALS) emergency ambulances with trained paramedics and portable ventilators.',
    contact: {
      phone: '+91 99000 11223',
      email: 'dispatch@rapidrescue.com',
    },
    address: {
      street: 'Central Ambulance Depot, Ring Road',
      city: 'Central City',
      state: 'State Central',
      pincode: '400003',
      fullAddress: 'Central Ambulance Depot, Ring Road, Central City - 400003',
    },
    location: {
      type: 'Point',
      coordinates: [72.8730, 19.0720],
    },
    availability: {
      status: 'AVAILABLE',
      notes: '12 active ambulances on standby with 10-15 min ETA.',
      lastUpdated: new Date(Date.now() - 2 * 60000).toISOString(),
    },
    operatingHours: '24/7 Emergency Dispatch',
    verified: true,
    rating: 4.9,
    reviewsCount: 410,
    distanceKm: 1.2,
    status: 'ACTIVE',
    createdAt: new Date('2026-01-05').toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'res-7',
    name: 'St. Jude Night Shelter & Safe Haven',
    category: 'Shelters',
    description: 'Clean, secure shelter offering beds, warm blankets, basic medical checkups, and assistance for displaced persons.',
    contact: {
      phone: '+91 97777 66554',
      email: 'care@stjudeshelter.org',
    },
    address: {
      street: '22 Old City Gate, Near Clock Tower',
      city: 'Central City',
      state: 'State Central',
      pincode: '400008',
      fullAddress: '22 Old City Gate, Near Clock Tower, Central City - 400008',
    },
    location: {
      type: 'Point',
      coordinates: [72.8880, 19.0620],
    },
    availability: {
      beds: 24,
      status: 'AVAILABLE',
      notes: 'Separate dormitories for families, men, and women.',
      lastUpdated: new Date(Date.now() - 30 * 60000).toISOString(),
    },
    operatingHours: '6:00 PM - 8:00 AM Daily',
    verified: true,
    rating: 4.8,
    reviewsCount: 78,
    distanceKm: 3.5,
    status: 'ACTIVE',
    createdAt: new Date('2026-02-10').toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    _id: 'res-8',
    name: 'Global Diagnostics & Drive-Thru Testing Center',
    category: 'Testing Centers',
    description: 'ICMR approved diagnostic lab providing RT-PCR, blood panels, HRCT chest scans, and home sample collection.',
    contact: {
      phone: '+91 98444 33221',
      email: 'reports@globaldiagnostics.com',
    },
    address: {
      street: '90 Park Avenue, West Wing',
      city: 'Central City',
      state: 'State Central',
      pincode: '400012',
      fullAddress: '90 Park Avenue, West Wing, Central City - 400012',
    },
    location: {
      type: 'Point',
      coordinates: [72.8680, 19.0830],
    },
    availability: {
      status: 'AVAILABLE',
      notes: 'Reports delivered within 6 hours online.',
      lastUpdated: new Date(Date.now() - 120 * 60000).toISOString(),
    },
    operatingHours: '6:00 AM - 9:00 PM',
    verified: true,
    rating: 4.5,
    reviewsCount: 160,
    distanceKm: 2.9,
    status: 'ACTIVE',
    createdAt: new Date('2026-02-05').toISOString(),
    updatedAt: new Date().toISOString(),
  }
];

export const MOCK_STATS: PlatformStats = {
  verifiedResources: 12480,
  availableServices: 3214,
  activeVolunteers: 486,
  emergencySupportCoverage: '24/7 Instant',
  hospitalsCount: 840,
  pharmaciesCount: 1950,
  oxygenSuppliersCount: 420,
  bloodBanksCount: 310,
};

export const MOCK_WEATHER: WeatherInfo = {
  city: 'Central City',
  temperature: 28.5,
  condition: 'Partly Cloudy',
  humidity: 65,
  windSpeed: 14,
  rainProbability: 20,
  highTemp: 31,
  lowTemp: 24,
  alert: {
    title: 'High Humidity & Heat Advisory',
    severity: 'INFO',
    description: 'Hydration centers and public water points are active across Central City transit hubs.',
  },
};

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    _id: 'notif-1',
    userId: 'user-curr',
    title: 'New Emergency Beds Added',
    message: 'City Care Hospital added 15 new ICU beds and updated oxygen supply.',
    type: 'RESOURCE_UPDATE',
    read: false,
    createdAt: new Date(Date.now() - 25 * 60000).toISOString(),
  },
  {
    _id: 'notif-2',
    userId: 'user-curr',
    title: 'Complaint Resolved',
    message: 'Your report regarding Apex LifeCare Pharmacy operating hours was verified and updated by admin.',
    type: 'COMPLAINT_UPDATE',
    read: false,
    createdAt: new Date(Date.now() - 180 * 60000).toISOString(),
  },
  {
    _id: 'notif-3',
    userId: 'user-curr',
    title: 'Weather Warning Update',
    message: 'Light rain expected tonight. Public shelters in Sector 4 are prepared with extra blankets.',
    type: 'WEATHER',
    read: true,
    createdAt: new Date(Date.now() - 720 * 60000).toISOString(),
  },
];

export const MOCK_EMERGENCY_REQUESTS: EmergencyRequest[] = [
  {
    _id: 'emg-101',
    requestId: 'EMG-89421',
    userId: 'user-101',
    userName: 'Anita Sharma',
    userPhone: '+91 98765 99887',
    location: {
      type: 'Point',
      coordinates: [72.8777, 19.0760],
    },
    addressString: 'Near Metro Pillar 142, MG Road, Central City',
    type: 'Medical',
    description: 'Acute respiratory distress and high fever. Needs immediate ambulance dispatch.',
    nearestHospital: {
      name: 'City Care Multi-Specialty Hospital',
      distance: '1.8 km',
      phone: '+91 98765 43210',
    },
    nearestAmbulance: {
      name: 'RapidRescue ALS Fleet Unit #4',
      distance: '1.2 km',
      phone: '+91 99000 11223',
    },
    status: 'IN_PROGRESS',
    createdAt: new Date(Date.now() - 12 * 60000).toISOString(),
  },
  {
    _id: 'emg-102',
    requestId: 'EMG-89422',
    userId: 'user-102',
    userName: 'Rajesh Kumar',
    userPhone: '+91 98111 00998',
    location: {
      type: 'Point',
      coordinates: [72.8600, 19.0920],
    },
    addressString: 'Industrial Estate Phase II, Central City',
    type: 'Oxygen',
    description: 'Urgent oxygen cylinder replacement needed for home patient.',
    nearestHospital: {
      name: 'PureAir Emergency Medical Oxygen Hub',
      distance: '0.8 km',
      phone: '+91 98111 22334',
    },
    status: 'ACKNOWLEDGED',
    createdAt: new Date(Date.now() - 35 * 60000).toISOString(),
  }
];

export const MOCK_COMPLAINTS: Complaint[] = [
  {
    _id: 'cmp-1',
    userId: 'user-105',
    userName: 'David Miller',
    userEmail: 'david@example.com',
    resourceId: 'res-2',
    resourceName: 'Apex LifeCare Pharmacy',
    subject: 'Incorrect phone number listed',
    description: 'The alternative landline number listed on the profile goes to a wrong line. Please fix.',
    priority: 'MEDIUM',
    status: 'RESOLVED',
    adminResponse: 'Verified and updated phone number with primary mobile contact.',
    createdAt: new Date('2026-02-14').toISOString(),
    updatedAt: new Date('2026-02-15').toISOString(),
  },
  {
    _id: 'cmp-2',
    userId: 'user-108',
    userName: 'Priya Verma',
    userEmail: 'priya@example.com',
    resourceId: 'res-4',
    resourceName: 'Sahya Community Relief Shelter',
    subject: 'Request for additional volunteer night shifts',
    description: 'Shelter is getting full after 8 PM on weekends. Extra volunteer presence recommended.',
    priority: 'HIGH',
    status: 'IN_PROGRESS',
    adminResponse: 'Assigned 2 extra weekend volunteer slots.',
    createdAt: new Date('2026-02-18').toISOString(),
  }
];

export const MOCK_VOLUNTEERS: Volunteer[] = [
  {
    _id: 'vol-1',
    userId: 'user-v1',
    name: 'Siddharth Rao',
    email: 'siddharth@example.com',
    phone: '+91 98234 56789',
    city: 'Central City',
    skills: ['Medical Support', 'Transportation', 'First Aid'],
    availability: 'IMMEDIATE',
    preferredRole: 'Emergency First Responder',
    status: 'ACTIVE',
    createdAt: new Date('2026-01-10').toISOString(),
  },
  {
    _id: 'vol-2',
    userId: 'user-v2',
    name: 'Meera Nair',
    email: 'meera@example.com',
    phone: '+91 97111 22233',
    city: 'Central City',
    skills: ['Food Distribution', 'Community Support', 'Logistics'],
    availability: 'WEEKENDS',
    preferredRole: 'Food Kitchen Lead',
    status: 'ACTIVE',
    createdAt: new Date('2026-01-22').toISOString(),
  }
];
